management:

  endpoint: # 활성화 여부 - 기본값 : 모두 활성화
    health:
#      show-components: always
      show-details: always
    env:
      show-values: never
#      enabled: true
#    beans:
#      enabled: false
#    caches:
#      enabled: true
#    heapdump:
#      enabled: true

  endpoints: # 노출 여부 - 활성화, 노출이 둘 다 되어 있어야 웹에서 확인 가능
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
#        exclude:
#          - beans

info: # /info에 표시할 env(환경 변수)를 설정
  name: jinwon
  age: 25
