management:
#  endpoint: # 활성화 여부 - 기본값 : 모두 활성화
#    health:
#      enabled: true
#    beans:
#      enabled: false
#    caches:
#      enabled: true
#    heapdump:
#      enabled: true
  endpoints: # 노출 여부 - 활성화, 노출이 둘 다 되어 있어야 웹에서 확인 가능
    web:
      exposure:
        include: "*"
#        exclude:
#          - beans
